apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-down
spec:
  schedule: "0 20 * * *" # запуск каждый день в 20:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scale-down
            image: k8s.gcr.io/kubectl:latest
            command:
              - /bin/sh
              - -c
              - kubectl scale deployment mindbox-deployment --replicas=1
          restartPolicy: OnFailure