apiVersion: v1
kind: Service
metadata:
  name: mindbox-service
spec:
  selector:
    app: mindbox-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # exposes service only inside cluster
